/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionHistoryGet A list of all Transactions in the transfer including reversals.
type TransactionHistoryGet struct {
	// The type of resource being returned: list.
	ResourceType *string `json:"resource_type,omitempty"`
	// Number of Transactions in the list. Details- Numeric Example: 1
	ItemCount *int64 `json:"item_count,omitempty"`
	Data *DataGet    `json:"data,omitempty"`
}

// NewTransactionHistoryGet instantiates a new TransactionHistoryGet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionHistoryGet() *TransactionHistoryGet {
	this := TransactionHistoryGet{}
	return &this
}

// NewTransactionHistoryGetWithDefaults instantiates a new TransactionHistoryGet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionHistoryGetWithDefaults() *TransactionHistoryGet {
	this := TransactionHistoryGet{}
	return &this
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *TransactionHistoryGet) GetResourceType() string {
	if o == nil || o.ResourceType == nil {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionHistoryGet) GetResourceTypeOk() (*string, bool) {
	if o == nil || o.ResourceType == nil {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *TransactionHistoryGet) HasResourceType() bool {
	if o != nil && o.ResourceType != nil {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *TransactionHistoryGet) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetItemCount returns the ItemCount field value if set, zero value otherwise.
func (o *TransactionHistoryGet) GetItemCount() int64 {
	if o == nil || o.ItemCount == nil {
		var ret int64
		return ret
	}
	return *o.ItemCount
}

// GetItemCountOk returns a tuple with the ItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionHistoryGet) GetItemCountOk() (*int64, bool) {
	if o == nil || o.ItemCount == nil {
		return nil, false
	}
	return o.ItemCount, true
}

// HasItemCount returns a boolean if a field has been set.
func (o *TransactionHistoryGet) HasItemCount() bool {
	if o != nil && o.ItemCount != nil {
		return true
	}

	return false
}

// SetItemCount gets a reference to the given int64 and assigns it to the ItemCount field.
func (o *TransactionHistoryGet) SetItemCount(v int64) {
	o.ItemCount = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TransactionHistoryGet) GetData() DataGet {
	if o == nil || o.Data == nil {
		var ret DataGet
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionHistoryGet) GetDataOk() (*DataGet, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TransactionHistoryGet) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given DataGet and assigns it to the Data field.
func (o *TransactionHistoryGet) SetData(v DataGet) {
	o.Data = &v
}

func (o TransactionHistoryGet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ResourceType != nil {
		toSerialize["resource_type"] = o.ResourceType
	}
	if o.ItemCount != nil {
		toSerialize["item_count"] = o.ItemCount
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionHistoryGet struct {
	value *TransactionHistoryGet
	isSet bool
}

func (v NullableTransactionHistoryGet) Get() *TransactionHistoryGet {
	return v.value
}

func (v *NullableTransactionHistoryGet) Set(val *TransactionHistoryGet) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionHistoryGet) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionHistoryGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionHistoryGet(val *TransactionHistoryGet) *NullableTransactionHistoryGet {
	return &NullableTransactionHistoryGet{value: val, isSet: true}
}

func (v NullableTransactionHistoryGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionHistoryGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


