/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GovernmentIds List of Government IDs.
type GovernmentIds struct {
	// URI describing the government ID. See 'Government ID URIs'.
	GovernmentIdUri []string `json:"government_id_uri,omitempty"`
}

// NewGovernmentIds instantiates a new GovernmentIds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGovernmentIds() *GovernmentIds {
	this := GovernmentIds{}
	return &this
}

// NewGovernmentIdsWithDefaults instantiates a new GovernmentIds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGovernmentIdsWithDefaults() *GovernmentIds {
	this := GovernmentIds{}
	return &this
}

// GetGovernmentIdUri returns the GovernmentIdUri field value if set, zero value otherwise.
func (o *GovernmentIds) GetGovernmentIdUri() []string {
	if o == nil || o.GovernmentIdUri == nil {
		var ret []string
		return ret
	}
	return o.GovernmentIdUri
}

// GetGovernmentIdUriOk returns a tuple with the GovernmentIdUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GovernmentIds) GetGovernmentIdUriOk() ([]string, bool) {
	if o == nil || o.GovernmentIdUri == nil {
		return nil, false
	}
	return o.GovernmentIdUri, true
}

// HasGovernmentIdUri returns a boolean if a field has been set.
func (o *GovernmentIds) HasGovernmentIdUri() bool {
	if o != nil && o.GovernmentIdUri != nil {
		return true
	}

	return false
}

// SetGovernmentIdUri gets a reference to the given []string and assigns it to the GovernmentIdUri field.
func (o *GovernmentIds) SetGovernmentIdUri(v []string) {
	o.GovernmentIdUri = v
}

func (o GovernmentIds) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GovernmentIdUri != nil {
		toSerialize["government_id_uri"] = o.GovernmentIdUri
	}
	return json.Marshal(toSerialize)
}

type NullableGovernmentIds struct {
	value *GovernmentIds
	isSet bool
}

func (v NullableGovernmentIds) Get() *GovernmentIds {
	return v.value
}

func (v *NullableGovernmentIds) Set(val *GovernmentIds) {
	v.value = val
	v.isSet = true
}

func (v NullableGovernmentIds) IsSet() bool {
	return v.isSet
}

func (v *NullableGovernmentIds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGovernmentIds(val *GovernmentIds) *NullableGovernmentIds {
	return &NullableGovernmentIds{value: val, isSet: true}
}

func (v NullableGovernmentIds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGovernmentIds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


