/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// P2pResponseRecipientAddress Address of the recipient in response.
type P2pResponseRecipientAddress struct {
	// First line of the recipient's address. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length: 1-50.
	Line1 *string `json:"line1,omitempty"`
	// Second line of the recipient's address. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length: 1-50.
	Line2 *string `json:"line2,omitempty"`
	// The recipient's city. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length: 1-25.
	City *string `json:"city,omitempty"`
	// The recipient's province, state or territory, as an ISO 3166-2 uppercase alpha 2 or 3 character country subdivision code. For example, Missouri is MO.
	CountrySubdivision *string `json:"country_subdivision,omitempty"`
	// The recipient's postal code. For USA, this is 5 digits or 5 digits hyphen 4 digits, for example '63368', '63368-5555'. For other regions, this is alphanumeric, length 1-10.
	PostalCode *string `json:"postal_code,omitempty"`
	// The recipient's country as an ISO 3166-1 uppercase alpha-3 country code; see [Country and Currency Codes](https://developer.mastercard.com/mastercard-send-person-to-person/documentation/field-uris-codes/country-currency-codes/). For example, the United States of America is USA.
	Country *string `json:"country,omitempty"`
}

// NewP2pResponseRecipientAddress instantiates a new P2pResponseRecipientAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewP2pResponseRecipientAddress() *P2pResponseRecipientAddress {
	this := P2pResponseRecipientAddress{}
	return &this
}

// NewP2pResponseRecipientAddressWithDefaults instantiates a new P2pResponseRecipientAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewP2pResponseRecipientAddressWithDefaults() *P2pResponseRecipientAddress {
	this := P2pResponseRecipientAddress{}
	return &this
}

// GetLine1 returns the Line1 field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetLine1() string {
	if o == nil || o.Line1 == nil {
		var ret string
		return ret
	}
	return *o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetLine1Ok() (*string, bool) {
	if o == nil || o.Line1 == nil {
		return nil, false
	}
	return o.Line1, true
}

// HasLine1 returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasLine1() bool {
	if o != nil && o.Line1 != nil {
		return true
	}

	return false
}

// SetLine1 gets a reference to the given string and assigns it to the Line1 field.
func (o *P2pResponseRecipientAddress) SetLine1(v string) {
	o.Line1 = &v
}

// GetLine2 returns the Line2 field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetLine2() string {
	if o == nil || o.Line2 == nil {
		var ret string
		return ret
	}
	return *o.Line2
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetLine2Ok() (*string, bool) {
	if o == nil || o.Line2 == nil {
		return nil, false
	}
	return o.Line2, true
}

// HasLine2 returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasLine2() bool {
	if o != nil && o.Line2 != nil {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given string and assigns it to the Line2 field.
func (o *P2pResponseRecipientAddress) SetLine2(v string) {
	o.Line2 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *P2pResponseRecipientAddress) SetCity(v string) {
	o.City = &v
}

// GetCountrySubdivision returns the CountrySubdivision field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetCountrySubdivision() string {
	if o == nil || o.CountrySubdivision == nil {
		var ret string
		return ret
	}
	return *o.CountrySubdivision
}

// GetCountrySubdivisionOk returns a tuple with the CountrySubdivision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetCountrySubdivisionOk() (*string, bool) {
	if o == nil || o.CountrySubdivision == nil {
		return nil, false
	}
	return o.CountrySubdivision, true
}

// HasCountrySubdivision returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasCountrySubdivision() bool {
	if o != nil && o.CountrySubdivision != nil {
		return true
	}

	return false
}

// SetCountrySubdivision gets a reference to the given string and assigns it to the CountrySubdivision field.
func (o *P2pResponseRecipientAddress) SetCountrySubdivision(v string) {
	o.CountrySubdivision = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetPostalCode() string {
	if o == nil || o.PostalCode == nil {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil || o.PostalCode == nil {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasPostalCode() bool {
	if o != nil && o.PostalCode != nil {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *P2pResponseRecipientAddress) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *P2pResponseRecipientAddress) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pResponseRecipientAddress) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *P2pResponseRecipientAddress) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *P2pResponseRecipientAddress) SetCountry(v string) {
	o.Country = &v
}

func (o P2pResponseRecipientAddress) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Line1 != nil {
		toSerialize["line1"] = o.Line1
	}
	if o.Line2 != nil {
		toSerialize["line2"] = o.Line2
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.CountrySubdivision != nil {
		toSerialize["country_subdivision"] = o.CountrySubdivision
	}
	if o.PostalCode != nil {
		toSerialize["postal_code"] = o.PostalCode
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	return json.Marshal(toSerialize)
}

type NullableP2pResponseRecipientAddress struct {
	value *P2pResponseRecipientAddress
	isSet bool
}

func (v NullableP2pResponseRecipientAddress) Get() *P2pResponseRecipientAddress {
	return v.value
}

func (v *NullableP2pResponseRecipientAddress) Set(val *P2pResponseRecipientAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableP2pResponseRecipientAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableP2pResponseRecipientAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableP2pResponseRecipientAddress(val *P2pResponseRecipientAddress) *NullableP2pResponseRecipientAddress {
	return &NullableP2pResponseRecipientAddress{value: val, isSet: true}
}

func (v NullableP2pResponseRecipientAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableP2pResponseRecipientAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


