/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// P2pReconciliationData Reconciliation information in response that will be associated to the transfer and will appear in the reconciliation reporting for the partner.
type P2pReconciliationData struct {
	// Contains custom field names and values to appear in the reconciliation report. This can be a list of multiple name/value pairs in response. The names provided must match the configured in the partner setup.
	CustomField []P2pCustomField `json:"custom_field,omitempty"`
}

// NewP2pReconciliationData instantiates a new P2pReconciliationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewP2pReconciliationData() *P2pReconciliationData {
	this := P2pReconciliationData{}
	return &this
}

// NewP2pReconciliationDataWithDefaults instantiates a new P2pReconciliationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewP2pReconciliationDataWithDefaults() *P2pReconciliationData {
	this := P2pReconciliationData{}
	return &this
}

// GetCustomField returns the CustomField field value if set, zero value otherwise.
func (o *P2pReconciliationData) GetCustomField() []P2pCustomField {
	if o == nil || o.CustomField == nil {
		var ret []P2pCustomField
		return ret
	}
	return o.CustomField
}

// GetCustomFieldOk returns a tuple with the CustomField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *P2pReconciliationData) GetCustomFieldOk() ([]P2pCustomField, bool) {
	if o == nil || o.CustomField == nil {
		return nil, false
	}
	return o.CustomField, true
}

// HasCustomField returns a boolean if a field has been set.
func (o *P2pReconciliationData) HasCustomField() bool {
	if o != nil && o.CustomField != nil {
		return true
	}

	return false
}

// SetCustomField gets a reference to the given []P2pCustomField and assigns it to the CustomField field.
func (o *P2pReconciliationData) SetCustomField(v []P2pCustomField) {
	o.CustomField = v
}

func (o P2pReconciliationData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CustomField != nil {
		toSerialize["custom_field"] = o.CustomField
	}
	return json.Marshal(toSerialize)
}

type NullableP2pReconciliationData struct {
	value *P2pReconciliationData
	isSet bool
}

func (v NullableP2pReconciliationData) Get() *P2pReconciliationData {
	return v.value
}

func (v *NullableP2pReconciliationData) Set(val *P2pReconciliationData) {
	v.value = val
	v.isSet = true
}

func (v NullableP2pReconciliationData) IsSet() bool {
	return v.isSet
}

func (v *NullableP2pReconciliationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableP2pReconciliationData(val *P2pReconciliationData) *NullableP2pReconciliationData {
	return &NullableP2pReconciliationData{value: val, isSet: true}
}

func (v NullableP2pReconciliationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableP2pReconciliationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


