/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sender Information about the sender of the transaction. Conditional. If a 'pan' or 'raw' scheme is provided in the `sender_account_uri`, this `sender` object is required. If you provide this object, you must provide `first_name`, `last_name`, and the `address` object.
type Sender struct {
	// Required. The sender's first name. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length 1-40. If you cannot provide the actual value, you must provide the alternative value '#NOTINCLUDED'.
	FirstName string `json:"first_name"`
	// The sender's middle name. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length 1-40.
	MiddleName *string `json:"middle_name,omitempty"`
	// Required. The sender's last name. Alphanumeric Special [a-zA-Z0-9 !\"#$%&'()*+,-./&#92;:;<=>?@[]_`{|}~ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïñòóôõöùúûüýÿ], length 1-40. If you cannot provide the actual value, you must provide the alternative value '#NOTINCLUDED'.
	LastName string `json:"last_name"`
	// The sender's nationality as an ISO 3166-1 uppercase alpha-3 country code; see [Country and Currency Codes](https://developer.mastercard.com/mastercard-send-person-to-person/documentation/field-uris-codes/country-currency-codes/). For example, the United States of America is USA.
	Nationality *string `json:"nationality,omitempty"`
	// The sender's date of birth in ISO 8601 full date format (YYYY-MM-DD). For example, 30 December 1999 is the value '1999-12-30'. Numeric and -, length 10.
	DateOfBirth *string `json:"date_of_birth,omitempty"`
	// Identifies the sender's account number type. This field is optional. Valid values: '00' Other, '01' RTN + Bank Account, '02' IBAN, '03' Card Account, '04' Email, '05' Phone Number, '06' Bank account number (BAN) + Bank Identification Сode (BIC), '07' Wallet ID, '08' Social Network ID. Numeric, 2 characters.
	AccountType *string              `json:"account_type,omitempty"`
	Address     RequestSenderAddress `json:"address"`
	// The sender's phone number including country code. Numeric, length 1-15.
	Phone *string `json:"phone,omitempty"`
	// The sender's email address. Alphanumeric Special [a-zA-Z0-9-@+.*$_], length 5-254.
	Email *string                `json:"email,omitempty"`
	GovernmentIds *GovernmentIds `json:"government_ids,omitempty"`
}

// NewSender instantiates a new Sender object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSender(firstName string, lastName string, address RequestSenderAddress) *Sender {
	this := Sender{}
	this.FirstName = firstName
	this.LastName = lastName
	this.Address = address
	return &this
}

// NewSenderWithDefaults instantiates a new Sender object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderWithDefaults() *Sender {
	this := Sender{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *Sender) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *Sender) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *Sender) SetFirstName(v string) {
	o.FirstName = v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *Sender) GetMiddleName() string {
	if o == nil || o.MiddleName == nil {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetMiddleNameOk() (*string, bool) {
	if o == nil || o.MiddleName == nil {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *Sender) HasMiddleName() bool {
	if o != nil && o.MiddleName != nil {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *Sender) SetMiddleName(v string) {
	o.MiddleName = &v
}

// GetLastName returns the LastName field value
func (o *Sender) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *Sender) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *Sender) SetLastName(v string) {
	o.LastName = v
}

// GetNationality returns the Nationality field value if set, zero value otherwise.
func (o *Sender) GetNationality() string {
	if o == nil || o.Nationality == nil {
		var ret string
		return ret
	}
	return *o.Nationality
}

// GetNationalityOk returns a tuple with the Nationality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetNationalityOk() (*string, bool) {
	if o == nil || o.Nationality == nil {
		return nil, false
	}
	return o.Nationality, true
}

// HasNationality returns a boolean if a field has been set.
func (o *Sender) HasNationality() bool {
	if o != nil && o.Nationality != nil {
		return true
	}

	return false
}

// SetNationality gets a reference to the given string and assigns it to the Nationality field.
func (o *Sender) SetNationality(v string) {
	o.Nationality = &v
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise.
func (o *Sender) GetDateOfBirth() string {
	if o == nil || o.DateOfBirth == nil {
		var ret string
		return ret
	}
	return *o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetDateOfBirthOk() (*string, bool) {
	if o == nil || o.DateOfBirth == nil {
		return nil, false
	}
	return o.DateOfBirth, true
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *Sender) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth != nil {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given string and assigns it to the DateOfBirth field.
func (o *Sender) SetDateOfBirth(v string) {
	o.DateOfBirth = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *Sender) GetAccountType() string {
	if o == nil || o.AccountType == nil {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetAccountTypeOk() (*string, bool) {
	if o == nil || o.AccountType == nil {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *Sender) HasAccountType() bool {
	if o != nil && o.AccountType != nil {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *Sender) SetAccountType(v string) {
	o.AccountType = &v
}

// GetAddress returns the Address field value
func (o *Sender) GetAddress() RequestSenderAddress {
	if o == nil {
		var ret RequestSenderAddress
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Sender) GetAddressOk() (*RequestSenderAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Sender) SetAddress(v RequestSenderAddress) {
	o.Address = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *Sender) GetPhone() string {
	if o == nil || o.Phone == nil {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetPhoneOk() (*string, bool) {
	if o == nil || o.Phone == nil {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *Sender) HasPhone() bool {
	if o != nil && o.Phone != nil {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *Sender) SetPhone(v string) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Sender) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Sender) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Sender) SetEmail(v string) {
	o.Email = &v
}

// GetGovernmentIds returns the GovernmentIds field value if set, zero value otherwise.
func (o *Sender) GetGovernmentIds() GovernmentIds {
	if o == nil || o.GovernmentIds == nil {
		var ret GovernmentIds
		return ret
	}
	return *o.GovernmentIds
}

// GetGovernmentIdsOk returns a tuple with the GovernmentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sender) GetGovernmentIdsOk() (*GovernmentIds, bool) {
	if o == nil || o.GovernmentIds == nil {
		return nil, false
	}
	return o.GovernmentIds, true
}

// HasGovernmentIds returns a boolean if a field has been set.
func (o *Sender) HasGovernmentIds() bool {
	if o != nil && o.GovernmentIds != nil {
		return true
	}

	return false
}

// SetGovernmentIds gets a reference to the given GovernmentIds and assigns it to the GovernmentIds field.
func (o *Sender) SetGovernmentIds(v GovernmentIds) {
	o.GovernmentIds = &v
}

func (o Sender) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["first_name"] = o.FirstName
	}
	if o.MiddleName != nil {
		toSerialize["middle_name"] = o.MiddleName
	}
	if true {
		toSerialize["last_name"] = o.LastName
	}
	if o.Nationality != nil {
		toSerialize["nationality"] = o.Nationality
	}
	if o.DateOfBirth != nil {
		toSerialize["date_of_birth"] = o.DateOfBirth
	}
	if o.AccountType != nil {
		toSerialize["account_type"] = o.AccountType
	}
	if true {
		toSerialize["address"] = o.Address
	}
	if o.Phone != nil {
		toSerialize["phone"] = o.Phone
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.GovernmentIds != nil {
		toSerialize["government_ids"] = o.GovernmentIds
	}
	return json.Marshal(toSerialize)
}

type NullableSender struct {
	value *Sender
	isSet bool
}

func (v NullableSender) Get() *Sender {
	return v.value
}

func (v *NullableSender) Set(val *Sender) {
	v.value = val
	v.isSet = true
}

func (v NullableSender) IsSet() bool {
	return v.isSet
}

func (v *NullableSender) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSender(val *Sender) *NullableSender {
	return &NullableSender{value: val, isSet: true}
}

func (v NullableSender) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSender) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


