/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransferWrapper Response details
type TransferWrapper struct {
	Transfer *Transfer `json:"transfer,omitempty"`
}

// NewTransferWrapper instantiates a new TransferWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferWrapper() *TransferWrapper {
	this := TransferWrapper{}
	return &this
}

// NewTransferWrapperWithDefaults instantiates a new TransferWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferWrapperWithDefaults() *TransferWrapper {
	this := TransferWrapper{}
	return &this
}

// GetTransfer returns the Transfer field value if set, zero value otherwise.
func (o *TransferWrapper) GetTransfer() Transfer {
	if o == nil || o.Transfer == nil {
		var ret Transfer
		return ret
	}
	return *o.Transfer
}

// GetTransferOk returns a tuple with the Transfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferWrapper) GetTransferOk() (*Transfer, bool) {
	if o == nil || o.Transfer == nil {
		return nil, false
	}
	return o.Transfer, true
}

// HasTransfer returns a boolean if a field has been set.
func (o *TransferWrapper) HasTransfer() bool {
	if o != nil && o.Transfer != nil {
		return true
	}

	return false
}

// SetTransfer gets a reference to the given Transfer and assigns it to the Transfer field.
func (o *TransferWrapper) SetTransfer(v Transfer) {
	o.Transfer = &v
}

func (o TransferWrapper) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transfer != nil {
		toSerialize["transfer"] = o.Transfer
	}
	return json.Marshal(toSerialize)
}

type NullableTransferWrapper struct {
	value *TransferWrapper
	isSet bool
}

func (v NullableTransferWrapper) Get() *TransferWrapper {
	return v.value
}

func (v *NullableTransferWrapper) Set(val *TransferWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferWrapper(val *TransferWrapper) *NullableTransferWrapper {
	return &NullableTransferWrapper{value: val, isSet: true}
}

func (v NullableTransferWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


