/*
Send Payment Transfer API

Mastercard Send Payment Transfer API

API version: 1.0.1
Contact: apisupport@mastercard.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PaymentTransferWrapper Contains the details of the request message.
type PaymentTransferWrapper struct {
	PaymentTransfer *PaymentTransfer `json:"payment_transfer,omitempty"`
}

// NewPaymentTransferWrapper instantiates a new PaymentTransferWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentTransferWrapper() *PaymentTransferWrapper {
	this := PaymentTransferWrapper{}
	return &this
}

// NewPaymentTransferWrapperWithDefaults instantiates a new PaymentTransferWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentTransferWrapperWithDefaults() *PaymentTransferWrapper {
	this := PaymentTransferWrapper{}
	return &this
}

// GetPaymentTransfer returns the PaymentTransfer field value if set, zero value otherwise.
func (o *PaymentTransferWrapper) GetPaymentTransfer() PaymentTransfer {
	if o == nil || o.PaymentTransfer == nil {
		var ret PaymentTransfer
		return ret
	}
	return *o.PaymentTransfer
}

// GetPaymentTransferOk returns a tuple with the PaymentTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentTransferWrapper) GetPaymentTransferOk() (*PaymentTransfer, bool) {
	if o == nil || o.PaymentTransfer == nil {
		return nil, false
	}
	return o.PaymentTransfer, true
}

// HasPaymentTransfer returns a boolean if a field has been set.
func (o *PaymentTransferWrapper) HasPaymentTransfer() bool {
	if o != nil && o.PaymentTransfer != nil {
		return true
	}

	return false
}

// SetPaymentTransfer gets a reference to the given PaymentTransfer and assigns it to the PaymentTransfer field.
func (o *PaymentTransferWrapper) SetPaymentTransfer(v PaymentTransfer) {
	o.PaymentTransfer = &v
}

func (o PaymentTransferWrapper) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PaymentTransfer != nil {
		toSerialize["payment_transfer"] = o.PaymentTransfer
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentTransferWrapper struct {
	value *PaymentTransferWrapper
	isSet bool
}

func (v NullablePaymentTransferWrapper) Get() *PaymentTransferWrapper {
	return v.value
}

func (v *NullablePaymentTransferWrapper) Set(val *PaymentTransferWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentTransferWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentTransferWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentTransferWrapper(val *PaymentTransferWrapper) *NullablePaymentTransferWrapper {
	return &NullablePaymentTransferWrapper{value: val, isSet: true}
}

func (v NullablePaymentTransferWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentTransferWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


